name: Run Tests on addTesting Branch

on:
  push:
    branches:
      - addTesting

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Run Jest tests
        run: npm test
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-test-results
          path: ./test-results/jest-junit.xml

      - name: Download test results
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: jest-test-results
          path: ./test-results

      - name: Display test results
        if: always()
        run: cat ./test-results/jest-junit.xml
