name: Run Tests and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests
      run: |
        npm test -- --coverage
        # Capture exit code of tests to handle failure
        echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/lcov-report # Ensure this path matches where your coverage report is generated

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: coverage/test-report.html # Ensure this path matches where your test results are generated
        if-no-files-found: warn
        include-hidden-files: false
